description: A generator showcasing the ironman hooks feature
hooks:
        pre_generate:
                - name: "echo"
                  args: ["-n", "Running pre-generate hook from test generator\n"]

        post_generate:
                - name: "echo"
                  args: ["-n", "Running post-generate hook from test generator\n"]
